apiVersion: v1
kind: Service
metadata:
  name: nginx-s-l
  labels:
    app: nginx
spec:
  type: LoadBalancer
  externalIPs:
  #- 192.168.1.199
  - 172.23.156.33
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
