apiVersion: v1
kind: Service
metadata:
  name: nginx-s-n
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 30000
      targetPort: 80
